name: Build & Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on:  ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Login ke Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3️⃣ Build Docker image
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/demo-app:latest .

      # 4️⃣ Push Docker image ke Docker Hub
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/demo-app:latest

      # 5️⃣ Setup kubeconfig (tidak perlu base64 karena runner di VM sama dengan cluster)
      - name: Setup kubeconfig
        run: |
          - name: Setup kubeconfig
            run: |
             mkdir -p $HOME/.kube
             echo "${{ secrets.KUBECONFIG_DATA }}" | base64 --decode > $HOME/.kube/config
             chmod 600 $HOME/.kube/config


      # 6️⃣ Debug kubeconfig
      - name: Debug kubeconfig
        run: |
          echo "Cek cluster info:"
          kubectl cluster-info
          echo "Cek nodes:"
          kubectl get nodes

      # 7️⃣ Deploy ke Kubernetes
      - name: Deploy to Kubernetes
        run: |
          kubectl get deployment demo-app || \
          kubectl create deployment demo-app --image=${{ secrets.DOCKER_USERNAME }}/demo-app:latest
          kubectl set image deployment/demo-app demo-app=${{ secrets.DOCKER_USERNAME }}/demo-app:latest
          kubectl expose deployment demo-app --type=NodePort --port=8080 || true
          kubectl get pods
          kubectl get svc
