jobs:
  deploy:
    runs-on: self-hosted   # gunakan self-hosted runner
    steps:
      - uses: actions/checkout@v3
      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build & Push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/demo-app:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/demo-app:latest
      - name: Deploy to K3s
        run: |
          if ! kubectl get deployment demo-app; then
            kubectl create deployment demo-app --image=${{ secrets.DOCKER_USERNAME }}/demo-app:latest
          fi
          kubectl set image deployment/demo-app demo-app=${{ secrets.DOCKER_USERNAME }}/demo-app:latest
          if ! kubectl get svc demo-app; then
            kubectl expose deployment demo-app --type=NodePort --port=8080
          fi
          kubectl get pods
          kubectl get svc
